import 'package:rallis/data/common/category_bean.dart';

List<CategoryBean> categoryBean() => [
      CategoryBean('Abstract', '',
          'https://img.freepik.com/free-vector/gradient-liquid-abstract-background_52683-60469.jpg?size=626&ext=jpg'),
      CategoryBean(
          'Nature', '', 'https://wallpaperaccess.com/full/1180075.jpg'),
      CategoryBean('Architecture', '',
          'https://static.dezeen.com/uploads/2021/05/oyo-architects-house-dede-belgium-residential-architecture_dezeen_sq3-411x411.jpg'),
      CategoryBean('Animals', '',
          'https://www.ucsf.edu/sites/default/files/2020-12/astonishing-animals-komodo-dragon-featured.jpg'),
      CategoryBean(
          'Portraits', '', 'https://jooinn.com/images/portrait-119.jpg'),
      CategoryBean(
          'Sea', '', 'https://i.ytimg.com/vi/QX4j_zHAlw8/maxresdefault.jpg'),
      CategoryBean('Night', '',
          'https://texasmotorplex.com/wp-content/uploads/2018/01/NightlightsRotator.jpg'),
      CategoryBean('Cars', '',
          'https://stimg.cardekho.com/images/carexteriorimages/360x240/Ferrari/Ferrari-488-GTB/047.jpg'),
      CategoryBean(
          'Street Art', '', 'https://wallpaperaccess.com/full/210623.jpg'),
      CategoryBean('Dark', '',
          'https://cdn.statically.io/img/www.wallpaperwolf.com/wallpapers/4k-wallpapers/4k/download/dark-forest-0131-4k.png'),
      CategoryBean(
          'Random', '', 'https://cdn.wallpapersafari.com/17/16/1lefPD.jpg'),
// CategoryBean('', '', ''),
    ];

List<CategoryBean> colorCategoryBean() => [
      CategoryBean('Black', '#000000',
          'https://c4.wallpaperflare.com/wallpaper/636/353/280/spider-man-wallpaper-preview.jpg'),
      CategoryBean('White', '#EDEADE',
          'https://bestwallpapers.in/wp-content/uploads/2018/04/cats-kitten-cute-white-brown-5k-wallpaper-2560x1600.jpg'),
      CategoryBean(
          'Yellow', '#FFFF00', 'https://wallpapercave.com/wp/wp8106092.jpg'),
      CategoryBean('Orange', '#FFA500',
          'https://miro.medium.com/max/4000/0*r-fg6tCOveGFWFsG.jpg'),
      CategoryBean('Red', '#FF0000',
          'https://images.hdqwalls.com/wallpapers/red-mask-neon-eyes-4k-0k.jpg'),
      CategoryBean('Purple', '#800080',
          'https://i.pinimg.com/originals/06/03/09/060309f2d6d87160af54dc9237376c3b.jpg'),
      CategoryBean('Magenta', '#FF00FF',
          'https://content.latest-hairstyles.com/wp-content/uploads/dark-purple-and-magenta-hair-color.jpg'),
      CategoryBean('Green', '#00FF00',
          'https://cdn.statically.io/img/wallpaperaccess.com/full/545792.jpg'),
      CategoryBean('Blue', '#0000FF',
          'https://www.printawallpaper.com/wp-content/uploads/2020/07/Blue_Guitar_on_Brick_Wall_dn.jpg'),
      CategoryBean('Teal', '#008080',
          'https://dukerichards.com/wp-content/uploads/2018/07/living-room-interior-design-blue-shade-1024x1024.jpg'),
      CategoryBean('black_and_white', '#c0c0c0',
          'https://i.pinimg.com/originals/a6/64/99/a66499d4c8e125576b61031b417605f8.jpg'),
    ];

List<CategoryBean> prodCategoryBean() => [
      CategoryBean('Insecticides', '',
          'https://5.imimg.com/data5/SELLER/Default/2021/5/GF/EH/SI/127347076/chess--500x500.jpeg'),
      CategoryBean('Fungicides', '',
          'https://pnwhandbooks.org/sites/pnwhandbooks/files/plant/images/fungicides-disease-control-home-landscape/homefungicides.jpg'),
      CategoryBean('Bio insecticides', '',
          'https://m.media-amazon.com/images/I/51UMnCDSbYL._SX466_.jpg'),
      CategoryBean('Acetochlor', '',
          'https://image.made-in-china.com/202f0j00pqOWvUEGnycn/Agrochemical-Herbicide-Weed-Acetochlor-Used-in-Farmland.jpg'),
      CategoryBean('Atrazine', '',
          'https://5.imimg.com/data5/RL/CA/PN/SELLER-18193757/atrazine-50-wp-500x500.jpg'),
      CategoryBean('Herbicides', '',
          'https://static.dezeen.com/uploads/2021/05/oyo-architects-house-dede-belgium-residential-architecture_dezeen_sq3-411x411.jpg'),
      CategoryBean('Rodenticides', '',
          'https://5.imimg.com/data5/NU/SJ/AK/SELLER-58999231/rodenticides-500x500.JPG'),
      CategoryBean('Algicides', '',
          'https://www.thepondshop.com.au/wp-content/uploads/2013/03/algaeproductpic.jpg'),
      CategoryBean('Germicides', '',
          'https://www.healthmark.ca/DATA/PRODUITIMAGE/1094.jpg'),
      CategoryBean('Herbicides', '',
          'https://www.stateindustrial.com/content/images/product/medium/117401_P.PNG'),
      CategoryBean('Treated Seeds', '',
          'https://5.imimg.com/data5/NI/PT/FM/SELLER-535538/seed-treatment-liquid-500x500.jpg'),
      CategoryBean('Molluscicides', '',
          'https://image.made-in-china.com/43f34j00REOUGPqssCba/Snail-Killer-Molluscicide-Tsp60-Camellia-Seeds-Extractiontea-Saponin-Kill-Snails-Slugs-for-Crop-Protection.jpg'),
      CategoryBean('Dark', '',
          'https://5.imimg.com/data5/TR/DO/ND/SELLER-35714845/sixer-bio-insecticides-500x500.jpg'),
     CategoryBean('Amitrole', '',
          'https://images.thdstatic.com/productImages/ca5705d5-0c57-4636-92f2-ffdd12dfa55c/svn/compare-n-save-weed-grass-killer-75325-64_1000.jpg'),
      CategoryBean('Herbicides ', '',
          'https://5.imimg.com/data5/NI/QT/MY-21252203/bhoocare-pretila-herbicide-500x500.jpg'),
    ];

List<CategoryBean> productBean() => [
      CategoryBean('Algicides', '',
          'https://www.syngenta.co.in/sites/g/files/zhg496/f/media/2021/03/15/in_main_banner.jpg'),
      CategoryBean('Germicides', '',
          'https://www.syngenta.co.in/sites/g/files/zhg496/f/media/2021/03/15/bannermasthead_fung.jpg'),
      CategoryBean('Molluscicides', '',
          'https://cen.acs.org/content/dam/cen/88/45/8845bus1color_live-1.jpg'),
      CategoryBean('Dark', '',
          'https://cdn.shopify.com/s/files/1/1537/5553/articles/How_To_Repot_a_Plant_7_1_1024x1024.png'),
      CategoryBean('Bio insecticides', '',
          'https://m.media-amazon.com/images/I/81kz2GpiiML._AC_SS450_.jpg'),
      CategoryBean('Multicrop', '',
          'https://www.glyndemitre10.com.au/store/wp-content/uploads/2019/05/multicrop_multiguard_valuepack.jpg'),
      CategoryBean('Market', '',
          'https://www.nexles.com/media/catalog/product/cache/18/thumbnail/500x/8083c875e83be300356bb052a4e4af68/a/u/au_190090_def_ps.png.jpg'),

      CategoryBean('Root Out', '',
          'https://5.imimg.com/data5/VQ/HT/VA/SELLER-6399641/root-out-herbicides-500x500.jpg'),
      CategoryBean('Insecticides', '',
          'https://5.imimg.com/data5/RL/CA/PN/SELLER-18193757/atrazine-50-wp-500x500.jpg'),
      CategoryBean('Fungicides', '',
          'https://5.imimg.com/data5/GH/CL/MY-26070815/fighter-fipronil-insecticides-500x500.jpg'),
      CategoryBean('Herbicides', '',
          'https://5.imimg.com/data5/UW/BM/TU/SELLER-88780051/tashan-agriculture-insecticides-500x500.jpg'),
      CategoryBean('Rodenticides', '',
          'https://static.connect2india.com/c2icd/company_resources/1944871/images/products/product-fipronil-5--sc-insecticide.jpg'),

      CategoryBean('Herbicides', '',
          'https://5.imimg.com/data5/OI/BG/MY-13324908/ultra-shield-biopesticides-500x500.jpg'),
      CategoryBean('Treated Seeds', '',
          'https://stimg.cardekho.com/images/carexteriorimages/360x240/Ferrari/Ferrari-488-GTB/047.jpg'),
     CategoryBean('Molluscicides', '',
          'https://marketresearch.biz/wp-content/uploads/2018/11/molluscicides-market-400x225.jpg'),
      CategoryBean('Ganick Organic', '',
          'https://www.candy.com.sg/6536-medium_default/mr-ganick-organic-molluscicide-baba.jpg'),
      CategoryBean('Snail Kill', '',
          'https://5.imimg.com/data5/EH/RG/PM/SELLER-23902400/snail-kill-molluscicide-500x500.jpg'),
      CategoryBean('Snail Slug', '',
          'https://5.imimg.com/data5/SELLER/Default/2020/11/PK/PU/XZ/20499726/snail-slug-spray-500x500.jpg'),
      CategoryBean('Slatic Net', '',
          'https://my-live-05.slatic.net/p/3dab839ff757286436a2038b4d622fb5.jpg.jpg_720x720q80.jpg'),
      CategoryBean('Agil Tcm', '',
          'https://farmagritech.com/wp-content/uploads/2019/11/Agil_tcm112-49211-2.jpg'),

      CategoryBean('Root', '',
          'https://img.agriexpo.online/images_ag/photo-m2/182661-14791619.jpg'),
      CategoryBean('Herbicides', '',
          'https://img.agriexpo.online/images_ag/photo-m2/185030-13183793.jpg'),
    ];

// https://anatisbioprotection.com/en/assets/images/news/bioceres-securite-2.png

List<CategoryBean> bannerProductBean() => [
CategoryBean('Insecticides', '',
'https://www.syngenta.co.in/sites/g/files/zhg496/f/media/2021/03/15/herbicides_masthead_banner_0.jpg'),
CategoryBean('Fungicides', '',
'https://www.syngenta.co.in/sites/g/files/zhg496/f/styles/syngenta_cta_teaser/public/media/2021/03/15/calaris_xtra_banner.jpg'),
CategoryBean('Herbicides', '',
'https://cdn.shopify.com/s/files/1/0080/3097/8128/articles/Herbicide_Decisions_1_800x.png'),
CategoryBean('Rodenticides', '',
'https://www.dhanuka.com/storage/category/May2019/7adKqeHdu1TN4SLCXaFk.jpg'),
CategoryBean('Algicides', '',
'https://www.adaalo.com/upload/Document/1617781744_dhanuka_thumb.jpg'),
CategoryBean('Germicides', '',
'https://content.indiainfoline.com/_media/iifl/img/misc/2015-04/18/full/dhanuka-agritech-1429350829-0423300.jpg'),
CategoryBean('Herbicides', '',
'https://i.pinimg.com/736x/fa/07/8f/fa078fe04ed91889780dbd9a46363f94.jpg'),
CategoryBean('Treated Seeds', '',
'https://i.ytimg.com/vi/isC1om904fk/maxresdefault.jpg')
];